version: "3"
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=statuscode..
    - POSTGRES_USER=statuscode
    - POSTGRES_DB=statuscodedb
  api:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - db