INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (1, 'Apache', 'Apache Web Server');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (2, 'Laravel', 'Laravel Framework');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (3, 'Spring', 'Spring Framework');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (4, 'Twitter', 'Twitter');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (5, 'cPanel', 'cPanel');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (6, 'ArcGIS', 'ArcGIS for Server');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (7, 'Cloudflare', 'Cloudflare');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (8, 'CloudFoundry', 'Cloud Foundry');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (9, 'Pantheon', 'Pantheon');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (10, 'IIS', 'Internet Information Services');
INSERT INTO public.sc_software (software_id, short_description, long_description) VALUES (11, 'nginx','nginx');
